### ISSUE TITLE
Enable pragma statements to be set on the connection

### ISSUE THREAD

**Issue by bricelam** [aspnet/DataCommon.SQLite#61]
We should enable certain [pragma statements](https://www.sqlite.org/pragma.html) to be set on the connection object then, every time we open the connection, we should issue them as commands.

Here are a few interesting ones that [ZSS](http://zumero.com/dev-center/zss/) recommends be set by default.

```SQL
PRAGMA foreign_keys = ON;
PRAGMA recursive_triggers = ON;
PRAGMA journal_mode = WAL;
```

**Comment by rowanmiller** [comment]
We don't need to do this in ADO.NET layer, we may handle some of it within the EF provider
